trigger:
  branches:
    include: ["master"]
pr:
  branches:
    include: ["master"]
  autoCancel: 'true'
  drafts: 'true'

jobs:
- template: testing-template.yml
  parameters:
    configs:
    - "image"
    - "icevision"
    - "vissl"
    - "text"
    - "tabular"
    - "video"
    gpu_inds:
    - "0"
    - "0,1"
